"""
This is a deterministic version of RAG, which I ended up not using.

This script bridges the gap between machine learning predictions and scientific
ground truth. It iterates through high-confidence drug-target pairs generated by a
Graph Neural Network (GNN) and dynamically queries PubMed to find existing
literature evidence supporting the predicted interactions for Parkinson's Disease.

Key functionality:
  - Load top drug-target repositioning predictions from GNN saliency outputs
  - Sanitize and simplify biological target names to optimize PubMed keyword matching
  - Batch query the NCBI E-utilities API (via ScientificRAG) for the top 20 candidates
  - Extract and format literature justifications (abstract snippets, PMIDs, dates)
  - Generate a validation dataset mapping model scores to real-world evidence availability

Output:
  - Console logs: Real-time progress, scores, and formatted abstract snippets
  - CSV file (rag_evidence.csv): A summary table containing drug IDs, target IDs,
    GNN scores, and boolean flags indicating if literature evidence was successfully found.

Dependencies:
  - pandas: Data loading and CSV generation
  - pathlib: Robust file path resolution
  - src.interpretability.rag.ScientificRAG: Custom PubMed retrieval engine
"""

import pandas as pd
from rag import ScientificRAG
from pathlib import Path


def simplify_target_name(full_name: str, max_words: int = 3) -> str:
    if not full_name or pd.isna(full_name):
        return ""
    name = full_name.strip()
    for suffix in [" (human)", " isoform", " subunit", " complex"]:
        if name.endswith(suffix):
            name = name.replace(suffix, "")

    words = name.split()
    return " ".join(words[:max_words])


def main():
    project_root = Path(__file__).resolve().parents[2]

    preds_file = project_root / "artifacts/gnn_v2/saliency_candidates_both.csv"
    try:
        top_preds = pd.read_csv(preds_file)
    except FileNotFoundError:
        print(f"File not found: {preds_file}")
        return

    output_file = project_root / "artifacts/gnn_v2/rag_evidence.csv"
    results = []

    rag = ScientificRAG(email="denisa.elena.nastasa@gmail.com")

    for idx, row in top_preds.head(20).iterrows():
        drug_id = row["drug_id"]
        drug_name = row.get("drug_name", drug_id)
        target_id = row["target_id"]
        target_name = row.get("target_name", target_id)
        score = row["score"]

        search_target_name = simplify_target_name(target_name, max_words=4)

        print(f"\n{'=' * 70}")
        print(f"#{idx + 1}: {drug_name} ({drug_id}) → {target_name} ({target_id})")
        print(f"Score: {score:.3f}")
        print(f"Searching PubMed with simplified name: '{search_target_name}'")
        print(f"{'=' * 70}")

        try:
            articles = rag.query_pubmed(drug_name, search_target_name, top_k=5)

            if articles:
                justification = rag.generate_justification(
                    drug_name, search_target_name, articles, max_items=3
                )
                print(justification)
                evidence_found = "Yes"
                num_articles = len(articles)
            else:
                print(f"No PubMed evidence found for '{drug_name}' + '{search_target_name}'")
                evidence_found = "No"
                num_articles = 0

            results.append({
                "rank": idx + 1,
                "drug_id": drug_id,
                "drug_name": drug_name,
                "target_id": target_id,
                "target_name": target_name,
                "gnn_score": score,
                "evidence_found": evidence_found,
                "num_articles": num_articles,
            })

        except Exception as e:
            print(f"[Error retrieving PubMed data]: {e}")
            results.append({
                "rank": idx + 1,
                "drug_id": drug_id,
                "drug_name": drug_name,
                "target_id": target_id,
                "target_name": target_name,
                "gnn_score": score,
                "evidence_found": "Error",
                "num_articles": 0,
            })

    results_df = pd.DataFrame(results)
    results_df.to_csv(output_file, index=False)
    print(f"\n[saved] Evidence summary → {output_file}")


if __name__ == "__main__":
    main()